---
- hosts: localhost
  become: yes
  vars_prompt:
  - name: ansible_become_password
    prompt: become password?
    private: yes
  - name: github_username
    prompt: github_username?
  vars:
    network_interface: "{{ ansible_default_ipv4.interface }}"
    current_user: "{{ lookup('env','USER') }}"
  tasks:
  - name: Manage /etc/sudoers.d directory
    file:
      path: /etc/sudoers.d
      state: directory

  - lineinfile:
      path: /etc/sudoers.d/{{ current_user }}
      line: "{{ current_user }} ALL=(root) NOPASSWD: ALL"
      create: true

  - name: Install required packages
    dnf:
      name:
      - openssh-server
      - avahi
      - nss-mdns
      state: present

  - name: Allow SSH through firewall
    firewalld:
      service: ssh
      permanent: yes
      state: enabled
      immediate: yes

  - name: Allow mDNS through firewall
    firewalld:
      service: mdns
      permanent: yes
      state: enabled
      immediate: yes

  - name: Open mDNS port in firewall
    firewalld:
      port: 5353/udp
      permanent: yes
      state: enabled
      immediate: yes

  - name: Start and enable SSH service
    systemd:
      name: sshd
      state: started
      enabled: yes

  - name: Start and enable Avahi daemon
    systemd:
      name: avahi-daemon
      state: started
      enabled: yes

  - name: Configure systemd-resolved for mDNS
    ini_file:
      path: /etc/systemd/resolved.conf
      section: Resolve
      option: MulticastDNS
      value: 'yes'
      no_extra_spaces: yes
    notify: restart systemd-resolved

  - name: Start and enable systemd-resolved
    systemd:
      name: systemd-resolved
      state: started
      enabled: yes

  - name: Configure nsswitch.conf for mDNS
    lineinfile:
      path: /etc/nsswitch.conf
      regexp: '^hosts:'
      line: 'hosts: files mdns4_minimal [NOTFOUND=return] dns myhostname'
      backup: yes

  - name: Configure systemd-networkd - Set interface name
    ini_file:
      path: /etc/systemd/network/10-{{ network_interface }}.network
      section: Match
      option: Name
      value: "{{ network_interface }}"
    notify: restart systemd-networkd

  - name: Configure systemd-networkd - Enable DHCP
    ini_file:
      path: /etc/systemd/network/10-{{ network_interface }}.network
      section: Network
      option: DHCP
      value: "yes"
    notify: restart systemd-networkd

  - name: Configure systemd-networkd - Enable mDNS
    ini_file:
      path: /etc/systemd/network/10-{{ network_interface }}.network
      section: Network
      option: MulticastDNS
      value: "yes"
    notify: restart systemd-networkd

  - name: Pull authroized keys from github
    authorized_key:
      key: http://github.com/{{ github_username }}.keys
      user: "{{ current_user }}"
    notify: restart sshd

  handlers:
  - name: restart systemd-resolved
    systemd:
      name: systemd-resolved
      state: restarted

  - name: restart systemd-networkd
    systemd:
      name: systemd-networkd
      state: restarted

  - name: restart sshd
    systemd:
      name: sshd
      state: restarted